<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Superdev.AspNetCore\Superdev.AspNetCore.csproj" />
    </ItemGroup>

</Project>
